### PR TITLE
Add function minifier for file cache minifier, post date as timeago like social media(optional), and CRUD Author via Admin panel

### PR DESCRIPTION
**Pull request by yayalaressa**
added minify function and it has been implemented on file caching

### CODE REVIEW

**Comment by yayalaressa** [comment]
untuk fungsi Minify HTML nya sudah saya uji di website saya mas [https://yaya.my.id](https://yaya.my.id)
hanya akan bekerja ketika file cache diaktifkan.

**Comment by danpros** [comment]
Hi thanks,

Can you make it optional? we can change it via settings (on and off).

**Comment by yayalaressa** [comment]
> Hi thanks,
> 
> Can you make it optional? we can change it via settings (on and off).

yes, i will make it. and then i will pull again.

**Comment by yayalaressa** [comment]
@danpros hello, i have successfully added feature "cache minify" and "timeago format as display posts date", the features is optional and can change it via settings. please check.

**Comment by yayalaressa** [comment]
Admin Panel with DataTables.JS <https://datatables.net/>

(Desktop Version)
Screenshot Datatables!

Mobile Version
Screenshot Datatables!

**Comment by yayalaressa** [comment]
@danpros hello, i have add menu Authors, so we can add multiple author via Admin panel
Screenshot Author!

**Comment by danpros** [comment]
Thanks,

For better communication you can reach me via dan[at]danpros.com

**Comment by yayalaressa** [comment]
@danpros siap mas

**Pull request closed without merging**
