### PR TITLE
Added Cloudflare Turnstile as alternative to Google reCAPTCHA

### PR DESCRIPTION
**Pull request by KuJoe**
Added the option to select Cloudflare's Turnstile instead of Google's reCAPTCHA for the login page due to it's less intrusive usage and better accessibility options.

@danpros this changes some of the variable names in the config.ini file, how would these variable names be updated for users who do the automatic update?

image
image

### CODE REVIEW

**Comment by danpros** [comment]
Thank you!

> how would these variable names be updated for users who do the automatic update?

They need to re configure it again, but it's fine. You need to remove the old config from configList.json so the old config will automatically show up in config/custom, they can copy paste it from there.

**Comment by danpros** [comment]
It would be great if we have new site wide config to disable MFA feature so we can hide those MFA input from login page.

**Comment by KuJoe** [comment]
> It would be great if we have new site wide config to disable MFA feature so we can hide those MFA input from login page.

Good idea, PR added.

In the future I will go through and find a better solution for handling MFA so it only prompts users with it enabled and only after they've authenticated with username and password, but I didn't want to rewrite the whole login process so this current implementation was the easiest solution for now.

**Comment by danpros** [comment]
Please, go ahead. You can go crazy with htmly but please make it as simple as possible. Performance, security, and simplicity is the key.

**Pull request merged**
