### PR TITLE
Admin: Add styles

### PR DESCRIPTION
**Pull request by techmsi**
* add styles to make the admin dashboard more appealing.

newadmin

### CODE REVIEW

**Comment by techmsi** [comment]
@danpros Please take a look when you have a chance.

**Comment by techmsi** [comment]
@danpros Please take a look when you have a chance.

**Comment by techmsi** [comment]
@danpros Please take a look when you have a chance.

**Comment by ncang** [comment]
@techmsi , see https://github.com/danpros/htmly/issues/358 @danpros he is busy

**Comment by danpros** [comment]
Thanks. Please see d1f7d27

**Pull request closed without merging**
