### PR TITLE
satu

### PR DESCRIPTION
**Pull request by irgaabd**
add font-awesome
add dropzone
add image uploader on admin interface

capture

### CODE REVIEW

**Comment by Kanti** [comment]
hi @irgaabd,

very nice change in the backend, thank you for your commitment.
If I test your changes it looks weird and I get this Error:`

``Fatal error: Call to undefined function get_my_posts() in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\testt\system\admin\views\main.html.php on line 5``

**Comment by irgaabd** [comment]
ah yes...

I added a "get_my_posts()" function to admin.php which return post to the viewer as an object
I personally prefer it instead of "get_recent_post()" which return a HTML table element, in a "purist" MVC senses. 
Just personal preference,

**Comment by ncang** [comment]
+1 contributor HTMLy, great job :+1:

**Comment by Kanti** [comment]
[need fix] if config setting jquery = "dsabled" nothing works

**Comment by Kanti** [comment]
### Should it look like this?
add-page
admin
import
posts

**Comment by irgaabd** [comment]
should work with jQuery disabled now..

and nope...its not supposed look like that 
I'll look into it,  just CSS glitch I supposed
I do trying to separate admin css with the themes css, cause I believe admin interface should be consistent and independent from the themes

**Comment by Kanti** [comment]
On page Admin, without any posts or pages:
``Warning: Invalid argument supplied for foreach() in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\testt\system\admin\views\main.html.php on line 6``

**Comment by danpros** [comment]
@irgaabd I already add image upload feature, please test it, especially from security side. You can work from this starting point :)

**Comment by irgaabd** [comment]
lagi di pelosok nih mas

**Comment by danpros** [comment]
@irgaabd wuih mudik ini pasti, nanti yang pull request ini mungkin akan saya close saja karena sudah tidak relevan. Dan malah lebih bagus misal kamu memulai dari versi yang sekarang :)

**Pull request closed without merging**
