### PR TITLE
Add support for PHP::SmartyPants

### PR DESCRIPTION
**Pull request by bluebirch**
Added support for PHP::SmartyPants, "a free web typography prettifyier tool for web writers. It easily translates plain ASCII punctuation characters into 'smart' typographic punctuation HTML entities" (<https://michelf.ca/projects/php-smartypants/>).

This functionality is controlled with the new `smart` configuration option.

Quotes can be customized and adapted to your preference.

I'm not a PHP developer but a psychologist, so please excuse if my code is slow and ineffective.

### CODE REVIEW

**Comment by danpros** [comment]
Hello,

Thanks for the pull but we should not use it. PHP markdown is enough because [PHP Markdown](https://github.com/michelf/php-markdown) actively developed so it's possible that this feature will be available either. 

Not to mention the occurrence of conflict because it is almost the same. https://stackedit.io

**Comment by bluebirch** [comment]
PHP::SmartyPants is from the same developer and is what is recommended if you want to convert quotes and dashes in PHP::Markdown, see for example https://github.com/michelf/php-markdown/issues/144.

**Comment by bluebirch** [comment]
May I bring this feature up for discussion once again?

**Comment by danpros** [comment]
Hello,

Can you make it optional? so we can on and off it via the settings.

**Comment by bluebirch** [comment]
It is optional and turned on with `smart = "true"` in the configuration. Further customization is possible with `doublequote.open`, `doublequote.close`, `singlequote.open` and `singlequote.close`.

**Comment by vdbhb59** [comment]
This sure sounds like a good option. :)

**Comment by danpros** [comment]
Apologies, I will close this one. Please create another pull request so it does not conflicted with the latest version.

**Comment by bluebirch** [comment]
Unfortunately, I don't use HTMLy anymore. I switched to a SSG.

**Comment by vdbhb59** [comment]
@bluebirch what is an SSG?
HTMLy is very useful and I found it to be perfect for me tbvh.

**Comment by danpros** [comment]
@bluebirch No problems 😄 

@vdbhb59 Its Static Site Generator.

**Pull request closed without merging**
