### PR TITLE
Translation & language corrections

### PR DESCRIPTION
**Pull request by vdbhb59**
* Added Gujarati Translation
* Updated Español Translation
* Corrected various sentence constructions
* Synced across all language packs

### CODE REVIEW

**Comment by vdbhb59** [comment]
There are still many changes left, all language based, but I did not have time to get to those. Please merge these changes, and I will pick up the rest when I can, maybe next month (not too sure).
@danpros

**Comment by danpros** [comment]
Hello,

I think you misinterpreted it "All posts tagged X" this mean we display all posts with tag X. You change it to "All tagged posts X"

**Comment by danpros** [comment]
And you just need to change the `.ini` value and not the key so no need to edit the PHP files.

**Comment by vdbhb59** [comment]
> Hello,
> 
> I think you misinterpreted it "All posts tagged X" this mean we display all posts with tag X. You change it to "All tagged posts X"

Ahh my bad. 🫣
I will change it. However, it really was confusing. 🙃

**Comment by danpros** [comment]
Its still work because key is just the key. 

Example if we have, key `comments` and value `About` in our language file:

```
comments = "About"
```
We call it in template file:

```php
<a href=""><?php echo i18n('comments');?></a>
```

Than resulting HTML:

```php
<a href="">About</a>
```

**Comment by vdbhb59** [comment]
> Its still work because key is just the key.
> 
> Example if we have, key `comments` and value `About` in our language file:
> 
> ```
> comments = "About"
> ```
> 
> We call it in template file:
> 
> ```
> <a href=""><?php echo i18n('comments');?></a>
> ```
> 
> Than resulting HTML:
> 
> ```
> <a href="">About</a>
> ```

Understood. But should the sentence construction be not correct? You can see the changes I did in all files are to correct them (other than the "all_posts_tagged", which was my misunderstanding)? Example _url_is_left_; _if_left_empty/blank_ are the correct statement. Should I at least keep those as I changed?

**Comment by danpros** [comment]
Yes no problems if you want to correct it, thank you for that. Besides, it's in the admin so it doesn't matter with the existing theme. Perhaps in the future we can simplify the key, example:

```
by_using_this_importer_you_are_agree_if_the_feed_is_yours_or_at_least_you_have_the_authority_to_publish_it
```

It would be great if in the future just, eg. `importer_warning` etc.

**Comment by vdbhb59** [comment]
> Yes no problems if you want to correct it, thank you for that. Besides, it's in the admin so it doesn't matter with the existing theme. Perhaps in the future we can simplify the key, example:
> 
> ```
> by_using_this_importer_you_are_agree_if_the_feed_is_yours_or_at_least_you_have_the_authority_to_publish_it
> ```
> 
> It would be great if in the future just, eg. `importer_warning` etc.

True, that makes sense. Minimal is better. :)

**Comment by vdbhb59** [comment]
@danpros mate, all done now. Good to go and merge. :)

**Comment by danpros** [comment]
Thank you! 😃

**Pull request merged**
